### ISSUE TITLE
Support for Cyrillic characters in the displayed Title

### ISSUE THREAD

**Issue by VladOliinyk** [A5H73Y/Parkour#331] opened 2022-10-27 14:15 UTC
Hello there! 

Unfortunately, right now the title containing Cyrillic characters looks like.. this:
![image 6](https://user-images.githubusercontent.com/5873850/198308991-e523139f-c6ce-4ad7-959e-7b87104f4c5e.png)

This is quite sad because Minecraft titles work fine with Cyrillic. I guess there are some troubles with UNICODE encoding.
So the only possible way to set up the Cyrillic title is to manually edit the course.json file and replace the display name with the Unicode text (https://unicode-table.com/en/tools/decoder/)

Thanks a lot <3

**Comment by VladOliinyk** [comment] 2022-10-27 15:04
Update: after the server restart, the encoding breaks, and the title looks crazy again 😣😥

**Comment by A5H73Y** [comment] 2022-11-05 19:16
Hi, Could you please provide more information as I've tried to replicate the issue you're having and cannot.
I've used this webite to find example characters: https://en.wikipedia.org/wiki/Cyrillic_script

Included a few in a default string.yml message and run it multiple times, reloading the config, restarting the server and nothing ever seems to break. Am I missing something?
<img width="487" alt="image" src="https://user-images.githubusercontent.com/6440871/200137084-8a81386e-d1dd-4fee-a769-e5cf81b0543e.png">

**Comment by VladOliinyk** [comment] 2022-11-05 19:32
Hello! Thanks for working on this ❤️

In my case, I was typing the course name in the game first, so the input was from my keyboard, just a few words. But them are displayed wrong, as on the screenshot I’ve attached to the first message.

The letters on your screenshot looks fine except a few ones that I’ve never ever seen before 😅

I’m off my pc now, so can’t test right now, but will update this thread asap. 

**But could you enter the Cyrillic words as a course title (that was displaying blue)?**

For examples, you can use this wikipedia article, just copy 1-2 words from anywhere. 
https://uk.m.wikipedia.org/wiki/%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B0 

Also, regarding the configs, when I’ve opened them with a SublimeText - the “name” also looks broken, as the displayed title in Minecraft, and I was trying to “Reopen with encoding…” feature in sublime, and that wasn’t help since the file is overwritten by the plugin (as I understand) after restart/reload.

Again, I will update the topic with my test cases asap. Will try to make it tomorrow, or on Monday.

**Comment by VladOliinyk** [comment] 2022-11-05 19:36
Anyway, here is few examples:
"Test route" :: "Тестовий маршрут"
"Don't even try" :: "Навіть не намагайся"
"Awesome run" :: "Чудовий забіг"

**Comment by Whitebrim** [comment] 2022-11-09 02:33
Cyrillic characters works fine for me, my `strings.yml` has UTF-8 encoding, maybe your `strings.yml` uses different encoding?(ASCII or Windows-1251)
![2022-11-09_05 31 13](https://user-images.githubusercontent.com/23287829/200722764-6e03d340-5a73-45b5-b1b4-c1ce9efda747.png)
[strings.yml](https://github.com/A5H73Y/Parkour/files/9966804/strings.txt)

**Comment by A5H73Y** [comment] 2022-11-20 10:57
I am closing this issue as I've not be able to replicate the issue and I've tried the scenario you've suggested:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/6440871/202898409-40de3f08-8b11-4585-a0ea-6da8d884a725.png">
<img width="481" alt="image" src="https://user-images.githubusercontent.com/6440871/202898429-e839885b-f87c-4770-acc9-07b20893d2e0.png">
As you mentioned I believe it's an encoding issue caused by your config editor, everything works as intended using VS Code so I know it's not a plugin issue.

**Closed by A5H73Y** 2022-11-20 10:57 UTC
