### ISSUE TITLE
Scoreboard bugging out when touching death block.

### ISSUE THREAD

**Issue by DrakePork** [A5H73Y/Parkour#264] opened 2021-01-19 22:08 UTC
When joining a parkour the scoreboard works fine, but as soon as I die from a death block the scoreboard disappears and I get these errors in console: [pastebin](https://mcpaste.io/117d9b1582bb2ac1)

The error also occurred on Parkour 6.2

**Comment by steve4744** [comment] 2021-01-21 14:36
Hi, do you have a plugin that tries to display a scoreboard when you die (when not playing parkour), e.g. something that counts number of deaths? It sounds as though another scoreboard is interfering with the Parkour scoreboard.

**Comment by DrakePork** [comment] 2021-01-21 15:38
I do have FeatherBoard, however that is disabled in the parkour world.

**Comment by A5H73Y** [comment] 2021-01-21 16:29
For process of elimination, could you temporarily uninstall the FeatherBoard plugin, restart the server and see if the problem still occurs? We have reason to believe it could be an external factor which is causing the Parkour plugin to lose track of the Scoreboard.

**Comment by DrakePork** [comment] 2021-01-21 17:01
Still happening after uninstalling FeatherBoard.

**Comment by steve4744** [comment] 2021-01-21 17:03
Could you pastebin the full startup log from the console? Or a plugin list, maybe we can recreate the error?
Thanks.

**Comment by DrakePork** [comment] 2021-01-21 18:06
[Startup Log](https://mcpaste.io/45dc362a0e0c9627)
![xvxcvxcvxcv](https://user-images.githubusercontent.com/29175884/105392665-58ddd880-5c13-11eb-851e-1546c1668d56.PNG)

**Comment by DrakePork** [comment] 2021-01-21 18:40
I have managed to narrow the search down to that its McMMO apparently that is causing it.

**Comment by DrakePork** [comment] 2021-01-21 19:38
Uh so resetting mcmmo folder and then putting the exact same settings as I had before back has somehow fixed it?

**Comment by steve4744** [comment] 2021-01-22 17:46
It seems like the issue is caused by the _teleport_ when you die rather than the death itself.

McMMO monitors teleport events and if your Parkour world is 'blacklisted' in McMMO then it removes the scoreboard, _even if scoreboards are disabled in McMMOs config_. I don't believe that is the correct behaviour so I've created a PR for it:  mcMMO-Dev/mcMMO#4400

If the Parkour world is not blacklisted then McMMO does nothing with the scoreboard - which maybe why its working for you now.

**Comment by A5H73Y** [comment] 2021-01-22 17:57
Awesome, great investigation and outcome @steve4744!

**Comment by steve4744** [comment] 2021-01-29 17:36
The bug in McMMO which has been fixed in release 2.1.173 of McMMO:
`Fixed a bug where scoreboards were torn down inappropriately when moving to or from blacklisted worlds`.

**Closed** 2021-01-30 11:24 UTC
